# Generated by Django 5.2.12 on 2026-03-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picturebook',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='繪本標題')),
                ('style', models.CharField(max_length=100, verbose_name='繪圖風格')),
                ('target_vocabulary', models.TextField(verbose_name='目標單字')),
                ('grade', models.CharField(max_length=50, verbose_name='適用年級')),
                ('lesson', models.CharField(max_length=100, verbose_name='單元名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picturebooks', to='accounts.student', verbose_name='所屬學生')),
            ],
        ),
    ]
