# Generated by Django 5.2.12 on 2026-03-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievementid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='成就名稱')),
                ('description', models.TextField(verbose_name='成就描述')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='成就圖示連結 (URL)')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解鎖時間')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='activities.achievement', verbose_name='解鎖成就')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.student', verbose_name='獲獎學生')),
            ],
            options={
                'unique_together': {('student', 'achievement')},
            },
        ),
    ]
