# Generated by Django 5.2.12 on 2026-03-22 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='活動名稱')),
                ('content', models.TextField(verbose_name='活動內容')),
                ('type', models.CharField(max_length=50, verbose_name='活動類型')),
                ('reward', models.IntegerField(verbose_name='獎勵積分')),
            ],
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon_url',
            field=models.URLField(blank=True, null=True, verbose_name='成就圖示連結'),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='activities.achievement'),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField(verbose_name='題目內容')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='正確答案')),
                ('options', models.TextField(verbose_name='選項(可用逗號分隔)')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='出題老師')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='測驗標題')),
                ('target_vocabulary', models.TextField(verbose_name='目標單字')),
                ('questions', models.ManyToManyField(related_name='quizzes', to='activities.question', verbose_name='包含題目')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='出題老師')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuizAttempt',
            fields=[
                ('attemptid', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(verbose_name='分數')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='作答時間')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.quiz', verbose_name='測驗卷')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='作答學生')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='指派時間')),
                ('due_date', models.DateTimeField(verbose_name='截止日期')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity', verbose_name='指定活動')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.class', verbose_name='指派班級')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='指派老師')),
            ],
        ),
    ]
