# Generated by Django 5.2.12 on 2026-03-09 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='班級名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('passwd', models.CharField(max_length=128, verbose_name='密碼')),
                ('total_points', models.IntegerField(default=0, verbose_name='總積分')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='暱稱')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('passwd', models.CharField(max_length=128, verbose_name='密碼')),
                ('total_points', models.IntegerField(default=0, verbose_name='總積分')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.teacher'),
        ),
    ]
